// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
//
// Hand-modified for dggridR: we deliberately do NOT include <Rcpp.h> in this
// translation unit.  Including <Rcpp.h> pulls in Rcpp/iostream/Rstreambuf.h
// which, when RCPP_USE_GLOBAL_ROSTREAM is not defined, places file-scope
// `static Rostream<true>  Rcout;` and `static Rostream<false> Rcerr;`
// objects into every including TU.  Their constructors run during
// dyn.load() before R is fully initialised for this .so, which crashes the
// CRAN pretest Debian box (R-devel, gcc-16, libstdc++-16, _FORTIFY_SOURCE=3)
// with `address (nil), cause 'memory not mapped'`.  RcppExports.cpp does not
// itself need any Rcpp:: types -- only the small set of R API entry points
// below -- so we include just those headers and replicate the RcppExport
// macro locally with the same visibility annotation Rcpp uses.

#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>

// Match Rcpp's own definition: extern "C" + attribute_visible.
#define RcppExport extern "C" attribute_visible

RcppExport SEXP dg_process_polydata_native(SEXP, SEXP);
RcppExport SEXP _rcpp_module_boot_gridgens();
RcppExport SEXP _rcpp_module_boot_gridstats();
RcppExport SEXP _rcpp_module_boot_dgfuncs();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_gridgens", (DL_FUNC) &_rcpp_module_boot_gridgens, 0},
    {"_rcpp_module_boot_gridstats", (DL_FUNC) &_rcpp_module_boot_gridstats, 0},
    {"_rcpp_module_boot_dgfuncs", (DL_FUNC) &_rcpp_module_boot_dgfuncs, 0},
    {"dg_process_polydata_native", (DL_FUNC) &dg_process_polydata_native, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dggridR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    // R_forceSymbols(dll, TRUE) is NOT used here: it makes
    // getNativeSymbolInfo() refuse to return the underscore-prefixed
    // `_rcpp_module_boot_*` entries that Rcpp's loadModule() looks up
    // at .onLoad() time, because they don't match the namespace's
    // `useDynLib(..., .fixes = "C_")` prefix.  Sticking with the pair
    // recommended in R-exts §5.4 -- registerRoutines + useDynamicSymbols
    // FALSE -- still confines every dyn.load lookup to the explicit
    // table below.
}
