export AR=ar
export CC=clang
export CXX=clang++
export CXX1X=clang++ --std=c++11

export CFLAGS = -g -O2 -Wall -Wno-unused -pedantic
export CXXFLAGS = -g -O2 -Wall -Wno-unused -pedantic
export CXX1XFLAGS = -g -O2 -Wall -Wno-unused -pedantic --std=c++11
export FFLAGS = -g -O2 -fbounds-check -mtune=native
export FCFLAGS = -g -O2 -fbounds-check -mtune=native


include Makevars
