export AR=ar
export CC=clang
export CXX=clang++
export CXX11=clang++

export CFLAGS = -g -O0 -Wall -Wno-unused -pedantic
export CXXFLAGS = -g -O0 -Wall -Wno-unused -pedantic
export CXX11FLAGS = -g -O0 -Wall -Wno-unused -pedantic --std=c++11
export FFLAGS = -g -O0 -fbounds-check -mtune=native
export FCFLAGS = -g -O0 -fbounds-check -mtune=native
export R_INCLUDE_DIR = /usr/share/R/include
export CLINK_CPPFLAGS = -I/home/rick/.R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include 
export CXX11PICFLAGS = -fPIC

include Makevars
